import type {
  DailyPestMonitoringData,
  DocumentDefinition,
  FlyCatcherData,
  LogColumn,
  LogSheetData,
  ServiceReportData,
  TrainingRecordData,
} from "../types";
import {
  CAPA_MODEL,
  CHECKPOINT_ISSUES,
  DEFAULT_READING_MODEL,
  EXCURSION_REMARKS,
  GENERIC_REJECTION_REASONS,
  JOBS_PER_SHIFT,
  JOB_POOL,
  LOT_DECISIONS,
  LOT_REASONS,
  OUTCOME_MIX,
  PO_SERIES,
  READING_MODELS,
  REJECTION_REASONS,
  SERVICE_REMARKS,
  SHIFT_ROSTER,
  SUBMIT_LAG_DAYS,
  VERIFY_LAG_DAYS,
  type CheckpointIssue,
  type ExcursionRemark,
  type JobSpec,
  type ReadingModel,
  type RejectionGround,
  type Weighted,
} from "../data/seed/plantPattern";
import { getLogSheetLayout } from "../data/seed/logSheetLayouts";
import { isOutOfBand } from "./validation";
import { isQuantityLine } from "./serviceMaterials";
import { addDays, compareISO, todayISO } from "../utils/date";
import { makeRng, type Rng } from "../utils/random";

// THE PLANT, SIMULATED. Applies the behaviour model in
// data/seed/plantPattern.ts (generated by tools/plant_pattern.py, calibrated
// against the company's own filled specimens and its Dec-2023 GAP report) to
// a given document and calendar date.
//
// Why this exists: a register in which every reading sits on nominal, every
// check point says Yes, every lot is Accepted and every record was verified
// the same afternoon is not a well-run plant — it is an obviously synthetic
// one, and an auditor spots it in seconds. What they look for is the
// exceptions and what was done about each. So this module produces the
// exceptions a real plant produces, and every one of them carries its
// consequence with it: the remark beside the reading, the action against the
// check point, the reason beside the lot status.
//
// Two rules make it safe to build records on:
//
//  1. DETERMINISTIC. Every value is derived from a seeded PRNG whose seed
//     names exactly what it decides ("reading|qc-viscosity|viscosity|
//     2026-08-14|11"). The same date reads the same way on every device, for
//     ever — an auditor can come back to 14-Aug and find the same 21.4 Sec.
//     reading and the same remark against it.
//  2. INDEPENDENT STREAMS. Each concern draws from its own seeded stream
//     rather than one shared sequence, so adding a value in one place cannot
//     silently re-roll every other value in the record.

// ---------------------------------------------------------------------------
// primitives

/** Box-Muller, so readings are normally distributed rather than triangular. */
function normal(rng: Rng, mean: number, sd: number): number {
  const u1 = Math.max(rng.next(), 1e-9);
  const u2 = rng.next();
  return mean + sd * Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

function round(value: number, decimals: number): number {
  const f = Math.pow(10, decimals);
  return Math.round(value * f) / f;
}

function weighted<T>(rng: Rng, options: Weighted<T>[]): T {
  const total = options.reduce((s, o) => s + o.weight, 0);
  let r = rng.next() * total;
  for (const o of options) {
    r -= o.weight;
    if (r <= 0) return o.value;
  }
  return options[options.length - 1].value;
}

function daysBetween(fromISO: string, toISO: string): number {
  return Math.round((Date.parse(toISO) - Date.parse(fromISO)) / 86400000);
}

// ---------------------------------------------------------------------------
// 1. Process readings — quiet noise, with the occasional drift episode

function modelFor(documentId: string, columnKey: string): ReadingModel {
  return READING_MODELS[`${documentId}.${columnKey}`] ?? READING_MODELS[`${documentId}.*`] ?? DEFAULT_READING_MODEL;
}

interface Episode {
  from: number;
  to: number;
  shift: number; // in the column's own unit, signed
}

/**
 * Does this reading drift on this date, and if so over which rows? Decided
 * once per (document, column, date) so a run of high readings is a run —
 * which is how a real process misbehaves, and what makes the Remark column
 * believable — rather than isolated spikes.
 */
function episodeFor(documentId: string, columnKey: string, dateISO: string, rowCount: number, halfBand: number): Episode | null {
  const model = modelFor(documentId, columnKey);
  const rng = makeRng(`episode|${documentId}|${columnKey}|${dateISO}`);
  if (!rng.chance(model.episodeRate)) return null;
  const length = Math.min(rowCount, rng.int(model.minLength, model.maxLength));
  const from = rng.int(0, Math.max(0, rowCount - length));
  const magnitude = model.minShift + rng.next() * (model.maxShift - model.minShift);
  const direction = rng.chance(0.6) ? 1 : -1; // processes run hot more often than cold
  return { from, to: from + length - 1, shift: direction * magnitude * halfBand };
}

export interface ReadingOutcome {
  value: number;
  /** Outside the printed acceptance band — the app highlights these and the
   *  QC report counts them. */
  outOfBand: boolean;
}

/**
 * One reading of a banded column. `nominalOverride` is for the set-point
 * columns that have a band but no printed nominal (the lamination sheets),
 * where the job's own set-point is the centre.
 */
export function readingFor(
  documentId: string,
  dateISO: string,
  col: LogColumn,
  rowIndex: number,
  rowCount: number,
  nominalOverride?: number
): ReadingOutcome {
  const min = col.min!;
  const max = col.max!;
  const nominal = nominalOverride ?? col.nominal ?? (min + max) / 2;
  const decimals = col.decimals ?? 2;
  const halfBand = (max - min) / 2;
  const model = modelFor(documentId, col.key);
  const sd = model.sigma ?? (model.sigmaFraction ?? 0.22) * halfBand;

  const episode = episodeFor(documentId, col.key, dateISO, rowCount, halfBand);
  const drift = episode && rowIndex >= episode.from && rowIndex <= episode.to ? episode.shift : 0;

  const rng = makeRng(`reading|${documentId}|${col.key}|${dateISO}|${rowIndex}`);
  const value = round(normal(rng, nominal + drift, sd), decimals);
  return { value, outOfBand: value < min || value > max };
}

/** The explanation an operator writes beside an out-of-band reading. */
export function excursionRemarkFor(documentId: string, dateISO: string, columnKey: string): ExcursionRemark | null {
  const options = EXCURSION_REMARKS[documentId];
  if (!options || options.length === 0) return null;
  return makeRng(`excursion|${documentId}|${columnKey}|${dateISO}`).pick(options);
}

// ---------------------------------------------------------------------------
// 2. Daily Pest Control Monitoring — the check points that fail

export interface CheckpointFinding extends CheckpointIssue {
  no: number;
}

/**
 * Which of the ten check points were answered the "finding" way on this date.
 * The wording is the company's own, from its Dec-2023 GAP Analysis Report:
 * the door closer, the utility-area gap, the fly killer found switched off,
 * the missing RBS numbering, material stacked against the wall. Check points
 * 7/8/9 are NOT decided here — rodent activity comes from the separate,
 * separately calibrated catch pattern (engine/rodentPattern.ts).
 */
export function checkpointFindingsFor(dateISO: string): CheckpointFinding[] {
  const out: CheckpointFinding[] = [];
  for (const [key, model] of Object.entries(CHECKPOINT_ISSUES)) {
    const no = Number(key);
    const rng = makeRng(`checkpoint|${no}|${dateISO}`);
    if (!rng.chance(model.rate)) continue;
    out.push({ no, ...rng.pick(model.issues) });
  }
  return out;
}

// ---------------------------------------------------------------------------
// 3. QC inspection records — how the lot was dispositioned

export interface LotOutcome {
  status: string;
  reason: string;
}

export function lotOutcomeFor(documentId: string, dateISO: string): LotOutcome {
  const rng = makeRng(`lot|${documentId}|${dateISO}`);
  const spec = weighted(
    rng,
    LOT_DECISIONS.map((d) => ({ value: d, weight: d.weight }))
  );
  if (!spec.reason) return { status: spec.status, reason: "" };
  const reasons = LOT_REASONS[documentId]?.[spec.reason];
  // A lot status other than Accepted without a reason beside it is exactly
  // what validation.ts blocks on submit, so never produce one.
  if (!reasons || reasons.length === 0) return { status: "Accepted", reason: "" };
  return { status: spec.status, reason: rng.pick(reasons) };
}

// ---------------------------------------------------------------------------
// 4. The jobs that ran

export interface JobRun extends JobSpec {
  poNo: string;
  startTime: string;
  endTime: string;
  inTimeHotroom: string;
}

function clockAfter(startMinutes: number): string {
  const m = ((startMinutes % 1440) + 1440) % 1440;
  return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}

/**
 * The jobs a lamination shift got through on this date, with their PO
 * numbers and clock times. Real sheets differ day to day — the same four
 * jobs at the same four times every day for a year is the tell that nobody
 * is really filling this in.
 */
export function jobsFor(dateISO: string): JobRun[] {
  const rng = makeRng(`jobs|${dateISO}`);
  const count = weighted(rng, JOBS_PER_SHIFT);
  // Rotate through the pool by date so consecutive days share some jobs (a
  // job usually runs over more than one shift) without repeating the lot.
  const offset = Math.abs(daysBetween(PO_SERIES.onDate, dateISO)) % JOB_POOL.length;
  const jobs: JobRun[] = [];
  let clock = 9 * 60 + rng.int(0, 25);
  for (let i = 0; i < count; i++) {
    const spec = JOB_POOL[(offset + i) % JOB_POOL.length];
    const run = Math.round(spec.runMinutes * (0.85 + rng.next() * 0.35));
    const start = clock;
    const end = start + run;
    // PO numbers climb with the calendar, as a real PO series does.
    const po = PO_SERIES.base + daysBetween(PO_SERIES.onDate, dateISO) * PO_SERIES.perDay + i;
    jobs.push({
      ...spec,
      poNo: String(po),
      startTime: clockAfter(start),
      endTime: clockAfter(end),
      inTimeHotroom: clockAfter(end + rng.int(5, 15)),
    });
    clock = end;
  }
  return jobs;
}

// ---------------------------------------------------------------------------
// 5. Service report remarks — and the findings a technician raises

export interface ServiceRemark {
  remark: string;
  finding?: { finding: string; correctiveAction: string };
}

export function serviceRemarkFor(variantKey: string | undefined, areaName: string, dateISO: string): ServiceRemark {
  const key = (variantKey ?? "").toLowerCase().includes("rodent")
    ? "rodent"
    : (variantKey ?? "").toLowerCase().includes("fly")
      ? "fly"
      : "general";
  const model = SERVICE_REMARKS[key];
  const rng = makeRng(`service|${key}|${areaName}|${dateISO}`);
  if (!rng.chance(model.findingRate)) return { remark: rng.pick(model.routine) };
  const hit = rng.pick(model.finding);
  return {
    remark: hit.remark,
    finding: hit.raisesFinding && hit.finding && hit.correctiveAction ? { finding: hit.finding, correctiveAction: hit.correctiveAction } : undefined,
  };
}

// ---------------------------------------------------------------------------
// 6. Who signed

export function qcSignerFor(time: string | undefined): string {
  const hour = Number((time ?? "09:00").split(":")[0]);
  return hour >= 18 || hour < 8 ? SHIFT_ROSTER.qc.night : SHIFT_ROSTER.qc.day;
}

/** Rotates the people who actually do a job, instead of always the first name in the list. */
export function rosterPick(role: "lamination" | "pestChecker" | "verifier", dateISO: string, fallback: string): string {
  const list = SHIFT_ROSTER[role];
  if (!list || list.length === 0) return fallback;
  return makeRng(`roster|${role}|${dateISO}`).pick(list);
}

// ---------------------------------------------------------------------------
// 7. How the record was signed off

export interface LifecycleOutcome {
  status: "In Progress" | "Pending Verification" | "Verified" | "Rejected";
  submittedBy?: string;
  submittedAt?: string;
  verifiedBy?: string;
  verifiedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}

// A clock time at the plant, stored the way the app stores every other time:
// as the UTC instant it was. Written straight out as "…T18:45:00.000Z" it was
// read back as UTC, so 18:45 at the plant showed as 00:15 the next day on any
// screen in India.
export function stampAt(dateISO: string, hour: number, minute: number): string {
  return new Date(Number(dateISO.slice(0, 4)), Number(dateISO.slice(5, 7)) - 1, Number(dateISO.slice(8, 10)), hour, minute).toISOString();
}

const isBlank = (v: unknown): boolean => String(v ?? "").trim() === "";

// The Remark column of a log sheet, by the issued key, a plant-added one's key
// or the heading itself — the same test engine/autoFill.ts writes remarks by.
const isRemarkColumn = (col: LogColumn): boolean => col.type === "text" && (/^remarks?(?:_|$)/i.test(col.key) || /^remarks?$/i.test(col.label.trim()));

/**
 * What this record itself shows that a verifier could send it back for — the
 * grounds each rejection reason in plantPattern.ts names (REQUIREMENTS §75).
 * Read from the record's own data, so a reason can only ever be given to a
 * record it is true of: "out-of-band reading not explained" to a sheet that
 * has one, "check point 8 answered Yes" to a register that answered Yes.
 */
export function rejectionGroundsFor(doc: DocumentDefinition, data: unknown): Set<RejectionGround> {
  const grounds = new Set<RejectionGround>();
  if (!data || typeof data !== "object") return grounds;
  switch (doc.kind) {
    case "daily-pest-monitoring": {
      const d = data as DailyPestMonitoringData;
      // A holiday row holds no round at all, so nothing about one can be wrong.
      if (d.isHoliday) break;
      if (isBlank(d.timeOfChecking)) grounds.add("time-of-checking-blank");
      if (d.checkpoints?.[8]?.value === "Yes" && isBlank(d.checkpoints[8].note)) grounds.add("checkpoint-8-location-blank");
      if (!isBlank(d.checker)) grounds.add("checker-written");
      break;
    }
    case "fly-catcher": {
      const entries = (data as FlyCatcherData).entries ?? [];
      const counted = (e: (typeof entries)[number]) => typeof e.catchCountApprox === "number";
      if (entries.some((e) => e.pcId === "PC-05" && counted(e))) grounds.add("pc-05-counted");
      if (entries.length === 13 && entries.filter((e) => !counted(e)).length === 2) grounds.add("two-of-13-counts-blank");
      break;
    }
    case "service-report": {
      const d = data as ServiceReportData;
      if (isBlank(d.customerSign)) grounds.add("customer-sign-blank");
      // Only the line that carries each material's quantity is asked for one
      // (engine/serviceMaterials.ts): the rest are blank by design.
      const lines = d.lines ?? [];
      if (lines.filter((l, i) => isQuantityLine(lines, i) && isBlank(l.qtyUsed)).length >= 3) grounds.add("three-quantities-blank");
      break;
    }
    case "training-record":
      if (isBlank((data as TrainingRecordData).certificateRef)) grounds.add("certificate-ref-blank");
      break;
    case "log-sheet": {
      const d = data as LogSheetData;
      const header = d.header ?? {};
      const layout = getLogSheetLayout(doc.id);
      if (layout) {
        const remark = layout.columns.find(isRemarkColumn);
        for (const row of d.rows ?? []) {
          if (!layout.columns.some((c) => isOutOfBand(c, row[c.key]))) continue;
          if (!remark) grounds.add("out-of-band-no-remark-column");
          else if (isBlank(row[remark.key])) grounds.add("out-of-band-remark-blank");
        }
      }
      if (!isBlank(header.shift) && (!isBlank(header.operatorName) || !isBlank(header.operator))) grounds.add("shift-and-operator-written");
      if (!isBlank(header.adhesiveBatch)) grounds.add("adhesive-batch-written");
      break;
    }
  }
  return grounds;
}

/** A reason this record holds the grounds for, or — holding none — one that speaks of nothing on it. */
function rejectionReasonFor(doc: DocumentDefinition, data: unknown, rng: Rng): string {
  const grounds = rejectionGroundsFor(doc, data);
  const supported = (REJECTION_REASONS[doc.kind] ?? []).filter((r) => grounds.has(r.when)).map((r) => r.reason);
  const generic = GENERIC_REJECTION_REASONS[doc.kind] ?? GENERIC_REJECTION_REASONS["*"];
  // One draw either way, so the reason never moves the rest of the stream.
  return rng.pick(supported.length > 0 ? supported : generic);
}

/**
 * What happened to this record after it fell due: who submitted it and when,
 * whether the verifier got to it the same day or a week later, whether it was
 * sent back. Every record submitted at 10:00 and verified at 15:00 is the
 * clearest tell that a dataset was generated, and a run of records with no
 * rejection anywhere in a year is the second clearest.
 *
 * `data` is what the record holds: a rejection reason is chosen from what it
 * shows (rejectionGroundsFor), never regardless of it.
 */
export function lifecycleFor(doc: DocumentDefinition, dueDate: string, submitter: string, verifier: string, today = todayISO(), data?: unknown): LifecycleOutcome {
  const rng = makeRng(`lifecycle|${doc.id}|${dueDate}`);
  const outcome = weighted(rng, OUTCOME_MIX);
  const submitLag = weighted(rng, SUBMIT_LAG_DAYS);
  const submittedOn = addDays(dueDate, submitLag);
  // Nothing can have been submitted in the future.
  if (compareISO(submittedOn, today) > 0 || outcome === "In Progress") {
    return { status: "In Progress" };
  }
  const submitted = {
    submittedBy: submitter,
    submittedAt: stampAt(submittedOn, rng.int(9, 18), rng.int(0, 59)),
  };

  if (outcome === "Rejected") {
    const rejectedOn = addDays(submittedOn, weighted(rng, VERIFY_LAG_DAYS));
    if (compareISO(rejectedOn, today) > 0) return { status: "Pending Verification", ...submitted };
    return {
      status: "Rejected",
      ...submitted,
      rejectedBy: verifier,
      rejectedAt: stampAt(rejectedOn, rng.int(10, 17), rng.int(0, 59)),
      rejectionReason: rejectionReasonFor(doc, data, rng),
    };
  }

  if (outcome === "Pending Verification") return { status: "Pending Verification", ...submitted };

  const verifiedOn = addDays(submittedOn, weighted(rng, VERIFY_LAG_DAYS));
  if (compareISO(verifiedOn, today) > 0) return { status: "Pending Verification", ...submitted };
  return {
    status: "Verified",
    ...submitted,
    verifiedBy: verifier,
    verifiedAt: stampAt(verifiedOn, rng.int(10, 18), rng.int(0, 59)),
  };
}

// ---------------------------------------------------------------------------
// 8. From a deviation to a corrective action

export interface FindingSchedule {
  targetDate: string;
  actualDateOfAction: string | null;
  status: "Open" | "Overdue" | "Closed";
}

/**
 * When a finding raised on `observedOn` was due to be closed, and whether it
 * actually was. This is the chain an auditor follows — observation, target
 * date, action taken, closure — so some of them are late and some are still
 * open, which is what the Dashboard's "Open Corrective Actions" counts.
 */
export function findingScheduleFor(seed: string, observedOn: string, today = todayISO()): FindingSchedule {
  const rng = makeRng(`finding|${seed}|${observedOn}`);
  const targetDate = addDays(observedOn, weighted(rng, CAPA_MODEL.targetDays));
  const closure = weighted(rng, CAPA_MODEL.closure);
  if (closure === "open") {
    return { targetDate, actualDateOfAction: null, status: compareISO(targetDate, today) < 0 ? "Overdue" : "Open" };
  }
  const closedOn =
    closure === "on-time"
      ? addDays(observedOn, Math.max(1, Math.round(daysBetween(observedOn, targetDate) * (0.3 + rng.next() * 0.6))))
      : addDays(targetDate, weighted(rng, CAPA_MODEL.lateDays));
  if (compareISO(closedOn, today) > 0) {
    return { targetDate, actualDateOfAction: null, status: compareISO(targetDate, today) < 0 ? "Overdue" : "Open" };
  }
  return { targetDate, actualDateOfAction: closedOn, status: "Closed" };
}
