import type {
  DailyPestMonitoringData,
  DocumentDefinition,
  FlyCatcherData,
  LogSheetData,
  LogSheetRow,
  MasterData,
  ServiceReportData,
  TrainingRecordData,
} from "../types";
import { formatMonthYearShort, fromISODate } from "../utils/date";
import { fixedMaterialForServiceArea } from "./serviceMaterials";
import { isCompanyHoliday } from "./holidays";
import { getLogSheetLayout } from "../data/seed/logSheetLayouts";
import { generateId } from "../utils/id";
import { newComplaintAckData } from "../data/seed/complaintAck";
import { newPestResponsibilitiesData } from "../data/seed/pestResponsibilities";
import { newServiceAgreementData } from "../data/seed/serviceAgreement";
import { termEnd } from "./serviceAgreement";

// Builds the AUTOMATIC / STATIC part of a new record shell (section 11 & 26):
// header info, checkpoint lists, PC locations, area lists are all
// pre-populated from master data so the user never re-types them. The
// ACTUAL OBSERVATION fields are left blank/null here — the assistant's
// auto-fill (engine/autoFill.ts) is what fills those in, separately and
// visibly, once a record actually falls due.
export function createDefaultData(
  doc: DocumentDefinition,
  dueDateISO: string,
  master: MasterData
): unknown {
  switch (doc.kind) {
    case "daily-pest-monitoring": {
      const data: DailyPestMonitoringData = {
        // Closed days — the Thursday weekly off and the leave calendar's
        // festival holidays, minus adjustment (working) days — arrive
        // pre-marked, like the "H O L I D A Y" rows on the paper register.
        isHoliday: isCompanyHoliday(dueDateISO, master),
        checkpoints: {},
        timeOfChecking: "",
        checker: "",
        summaryActions: [],
      };
      return data;
    }
    case "fly-catcher": {
      const d = fromISODate(dueDateISO);
      const data: FlyCatcherData = {
        monthYear: formatMonthYearShort(d.getFullYear(), d.getMonth()),
        entries: master.pcLocations.map((pc) => ({
          pcId: pc.id,
          catchCountApprox: null,
          tubeLightInstallDate: null,
          tubeLightDueDate: null,
          cleaningDoneBy: "",
          verifiedBy: "",
        })),
      };
      return data;
    }
    case "service-report": {
      const areas = master.areas.filter((a) => a.context === `service-report:${doc.variantKey}`);
      const data: ServiceReportData = {
        serviceName: doc.variantKey ?? doc.name,
        lines: areas.map((a, i) => {
          const fixed = fixedMaterialForServiceArea(doc.variantKey, a.name);
          return {
            slNo: i + 1,
            areaName: a.name,
            materialName: fixed.materialName,
            qtyUsed: "",
            methodOfApplication: fixed.methodOfApplication,
            remarks: "",
          };
        }),
        technicianSign: "",
        customerSign: "",
      };
      return data;
    }
    case "training-record": {
      // Yearly shells are generated by the frequency engine; the assistant
      // fills topics/attendees from the previous programme (autoFill.ts).
      const data: TrainingRecordData = {
        trainingDate: dueDateISO,
        trainingType: "",
        trainerProvider: "",
        topics: [],
        attendees: [],
        certificateRef: "",
        remarks: "",
      };
      return data;
    }
    case "complaint-ack":
      // A report is started by hand (As Required) — the form's own wording filled in, the rest blank.
      return newComplaintAckData(dueDateISO);
    case "pest-responsibilities":
      // Started by hand too: the agreement's own wording, for the two parties to agree and sign.
      return newPestResponsibilitiesData();
    case "service-agreement":
      // The provider's format for a two-year term starting on the due date —
      // normally created from the Service Provider page (engine/serviceAgreement.ts).
      return newServiceAgreementData(dueDateISO, termEnd(dueDateISO));
    case "log-sheet": {
      const layout = getLogSheetLayout(doc.id);
      const header: Record<string, string> = {};
      let rows: LogSheetRow[] = [];
      if (layout) {
        // A blank form may arrive with the routine parts already entered (the
        // shift, the machine), but never with a DECISION already made: the
        // Lot Status box of an inspection that has not happened yet must not
        // read "Accepted". It is filled when the record is prepared, and the
        // person who signs it is the one who decides.
        for (const f of [...layout.headerFields, ...(layout.footerFields ?? [])]) {
          header[f.key] = isDecisionField(f.key) ? "" : (f.autoFill?.default ?? "");
        }
        rows = emptyLogRows(doc.id);
      }
      const data: LogSheetData = { header, rows };
      return data;
    }
    default:
      return {};
  }
}

// The fields that record a judgement rather than a setting, and so are never
// pre-answered on a blank form (see createDefaultData above).
const isDecisionField = (key: string): boolean => key === "lotStatus" || key === "deviationReason";

// Blank grid rows for a log sheet: one per fixed time slot, exactly one for
// single-row layouts, or the minimum number of free rows.
export function emptyLogRows(documentId: string): LogSheetRow[] {
  const layout = getLogSheetLayout(documentId);
  if (!layout) return [];
  const blank = (): LogSheetRow => {
    const row: LogSheetRow = { id: generateId("row") };
    for (const c of layout.columns) row[c.key] = c.type === "number" ? null : c.fixed ? "" : c.autoFill?.default !== undefined && c.type !== "text" ? String(c.autoFill.default) : "";
    return row;
  };
  const mode = layout.rowMode;
  if (mode.kind === "timeSlots") {
    return mode.slots.map((slot) => ({ ...blank(), [mode.slotKey]: slot }));
  }
  if (mode.kind === "single") return [blank()];
  if (mode.kind === "fixedRows") return mode.rows.map((fixed) => ({ ...blank(), ...fixed }));
  return Array.from({ length: mode.minRows ?? 1 }, blank);
}
