import React, { useMemo, useState } from "react";
import { FiActivity, FiArrowRight, FiAward, FiBookOpen, FiCalendar, FiClipboard, FiDroplet, FiFileText, FiPrinter, FiTrendingUp, FiTruck } from "react-icons/fi";
import { useAppStore } from "../store/AppStore";
import { useRouter } from "../store/router";
import { pressable } from "../utils/pressable";
import { printDocument } from "../utils/print";
import { DownloadDocumentButton } from "../components/common/DownloadDocumentButton";
import { recordRepository } from "../data/repositories/recordRepository";
import { documentRepository } from "../data/repositories/documentRepository";
import { masterRepository } from "../data/repositories/masterRepository";
import { ensureRecordsGeneratedForMonth } from "../engine/recordGenerator";
import { scheduleLabel } from "../engine/frequencyEngine";
import { effectiveDueDatesInMonth } from "../engine/holidays";
import { getDocumentInfo } from "../engine/documentInfo";
import { countFindings } from "../engine/checkpoints";
import { totalRodents } from "../engine/rodentPattern";
import { flySeasonLabel } from "../engine/flyPattern";
import { fixedMaterialForServiceArea } from "../engine/serviceMaterials";
import { agreementStatus } from "../engine/serviceAgreement";
import { PR_DOC_ID, newPestResponsibilitiesData } from "../data/seed/pestResponsibilities";
import { generateId } from "../utils/id";
import { fliesInMonth, flyStatsForYear, rodentStatsForYear, rodentsInMonth } from "../data/selectors";
import { FlyCatcherTrendReport, LizardTrendReport, RodentTrendReport } from "./ReportsPage";
import { StatusBadge } from "../components/common/StatusBadge";
import { DemoTag } from "../components/common/DemoTag";
import { NotYourDepartment } from "../components/common/NotYourDepartment";
import { DailyRegisterSheet, FHR17_ORIGINAL_PAGES } from "../components/records/DailyRegisterSheet";
import { FlyCatcherRegisterSheet } from "../components/records/FlyCatcherRegisterSheet";
import { DocumentHeader } from "../components/documents/DocumentHeader";
import { useT } from "../i18n";
import { MONTH_NAMES, WEEKDAY_NAMES, compareISO, daysInMonth, formatDisplayDate, fromISODate, pad2, todayISO } from "../utils/date";
import type { DailyPestMonitoringData, DocumentDefinition, FlyCatcherData, PestResponsibilitiesData, RecordInstance, ServiceReportData, TrainingRecordData } from "../types";

// The Pest Control module, organised the way the department actually talks
// about its paperwork (and the way the source documents fall):
//   1. Daily Report          — Daily Pest Control Monitoring Record (F/HR/17)
//   2. Service Reports       — Gurudev Pest Control's fortnightly visit reports:
//                              Rat / Mice, Ants & Cockroaches, Fly Control
//   3. Trend Analysis        — Rodent Catch Report & Trend, Fly Catcher Infestation
//   4. Training & Reference  — Training Records, Chemical Master, the licence
// Each group gets its own page here. The records themselves still open in
// the shared RecordPage (/record/{id}) and are still generated by the
// frequency engine — these pages are the department's way in, not a second
// copy of the data.

const DAILY_DOC_ID = "daily-pest-monitoring";
const FLY_DOC_ID = "fly-catcher";
const TRAINING_DOC_ID = "training-record";
const DONE_STATUSES = new Set(["Submitted", "Pending Verification", "Verified"]);

export const PEST_SERVICES: Record<string, { docId: string; title: string; pests: string }> = {
  rodent: { docId: "service-report-rodent", title: "Rat / Mice — Rodent Control Service", pests: "Rat, Mice & Bandicoots" },
  general: { docId: "service-report-general", title: "Ants & Cockroaches — General Pest Control Services", pests: "Red & Black Ants, Cockroaches" },
  fly: { docId: "service-report-fly", title: "Fly Control Services", pests: "House Fly" },
};

// ---------------------------------------------------------------------------
// shared helpers

function monthRange(year: number, month: number) {
  return { fromDate: `${year}-${pad2(month + 1)}-01`, toDate: `${year}-${pad2(month + 1)}-${pad2(daysInMonth(year, month))}` };
}

// First due date on/after `fromISO` (looks up to 13 months ahead), holiday-
// aware: a visit scheduled on the Thursday weekly off is due on the Friday.
export function nextDueDate(doc: DocumentDefinition, fromISO: string): string | null {
  const master = masterRepository.get();
  const d = fromISODate(fromISO);
  let y = d.getFullYear();
  let m = d.getMonth();
  for (let i = 0; i < 13; i++) {
    const hit = effectiveDueDatesInMonth(doc, y, m, master)
      .map((x) => x.due)
      .find((iso) => compareISO(iso, fromISO) >= 0);
    if (hit) return hit;
    m += 1;
    if (m > 11) {
      m = 0;
      y += 1;
    }
  }
  return null;
}

function latestRecord<T>(docId: string, isDemo: boolean, uptoISO: string): RecordInstance<T> | undefined {
  return (recordRepository.query({ documentId: docId, isDemo, toDate: uptoISO }) as RecordInstance<T>[])
    .slice()
    .sort((a, b) => compareISO(b.dueDate, a.dueDate))[0];
}

// Live records for the month being looked at (the engine applies the
// launch-date floor itself, so browsing old months never fabricates a
// backlog — see engine/recordGenerator.ts).
function useEnsureMonth(year: number, month: number, version: number) {
  useMemo(() => {
    ensureRecordsGeneratedForMonth(year, month, { isDemo: false });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [year, month, version]);
}

// A year that hasn't happened holds no records, and the trend reports drop it
// (data/selectors.ts keeps years up to this one), so offering it only produced
// an empty table row and a bare chart captioned "the chart shows 2027"
// (REQUIREMENTS §39). The year after this one is therefore not offered.
function YearSelect({ value, onChange }: { value: number; onChange: (y: number) => void }) {
  const thisYear = new Date().getFullYear();
  const years = [value - 1, value, value + 1].filter((y) => y <= thisYear);
  return (
    <select className="input input-sm" style={{ width: 90 }} data-select="year" value={value} onChange={(e) => onChange(Number(e.target.value))}>
      {years.map((y) => (
        <option key={y} value={y}>
          {y}
        </option>
      ))}
    </select>
  );
}

function MonthSelect({ value, onChange }: { value: number; onChange: (m: number) => void }) {
  return (
    <select className="input input-sm" style={{ width: 140 }} value={value} onChange={(e) => onChange(Number(e.target.value))}>
      {MONTH_NAMES.map((n, i) => (
        <option key={n} value={i}>
          {n}
        </option>
      ))}
    </select>
  );
}

function rodentCellFor(r: RecordInstance<DailyPestMonitoringData> | undefined): string {
  if (!r || r.data.isHoliday || r.data.checkpoints[7]?.value !== "Yes") return "";
  const catches = r.data.rodentCatches ?? [];
  if (catches.length === 0) return "Yes (details not recorded)";
  return `${totalRodents(catches)} — ${catches.map((c) => `${c.trapBoxNo || "?"} ${c.location}`).join("; ")}`;
}

export function DocMeta({ doc }: { doc: DocumentDefinition }) {
  const info = getDocumentInfo(doc, masterRepository.get());
  return (
    <div className="text-xs text-muted">
      Format {doc.formatNo}
      {doc.revisionNo && doc.revisionNo !== "TO BE CONFIRMED" ? ` (Rev ${doc.revisionNo})` : ""} · {scheduleLabel(doc)} · {info.whoLabel} ·{" "}
      <span className="text-faint">Source: {doc.sourceFile}</span>
    </div>
  );
}

// ---------------------------------------------------------------------------
// 0. Module overview — /pest-control

export function PestControlOverviewPage() {
  const { mode, version } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const today = todayISO();
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth();
  useEnsureMonth(year, month, version);

  const docs = documentRepository.getAll();
  const master = masterRepository.get();
  const dailyDoc = docs.find((d) => d.id === DAILY_DOC_ID);
  const todayRecord = recordRepository.query({ documentId: DAILY_DOC_ID, isDemo, dueDate: today })[0] as RecordInstance<DailyPestMonitoringData> | undefined;
  const monthDaily = recordRepository.query({ documentId: DAILY_DOC_ID, isDemo, ...monthRange(year, month) }) as RecordInstance<DailyPestMonitoringData>[];
  const daysRecorded = monthDaily.filter((r) => DONE_STATUSES.has(r.status)).length;
  const awaiting = monthDaily.filter((r) => !r.data.isHoliday && !DONE_STATUSES.has(r.status) && compareISO(r.dueDate, today) <= 0).length;
  const findings = monthDaily.reduce((s, r) => s + (r.data.isHoliday ? 0 : countFindings(master.checkpoints, r.data.checkpoints)), 0);
  const rodentsMonth = rodentsInMonth(year, month, isDemo);
  const rodentsYear = rodentStatsForYear(year, isDemo).total;
  const fliesMonth = fliesInMonth(year, month, isDemo);
  const fliesYear = flyStatsForYear(year, isDemo).total;

  const services = Object.entries(PEST_SERVICES).map(([slug, s]) => {
    const doc = docs.find((d) => d.id === s.docId);
    const last = doc ? latestRecord<ServiceReportData>(doc.id, isDemo, today) : undefined;
    const next = doc ? nextDueDate(doc, today) : null;
    return { slug, ...s, doc, last, next };
  });
  const flyDoc = docs.find((d) => d.id === FLY_DOC_ID);
  const nextFly = flyDoc ? nextDueDate(flyDoc, today) : null;
  const lastTraining = latestRecord<TrainingRecordData>(TRAINING_DOC_ID, isDemo, today);

  // WHOSE PAPERWORK THIS SHELF HOLDS. Every format in the pest control file
  // belongs to Human Resources on the company's own Master List of Formats
  // (data/seed/departments.ts), so somebody from another department who
  // reaches /pest-control by an old bookmark or a link must not be shown
  // these cards: a card names a document, prints its format number, counts
  // the month on it and offers to open it, which is already more than they
  // may see (REQUIREMENTS §40). This page is a shelf of several documents
  // rather than one document, so a card is left out when its own document is
  // outside the viewer's departments instead of the whole page being
  // refused. When that leaves nothing, the refusal takes the page's place:
  // the only reason every card can be missing is the viewer's department,
  // and only the refusal says whose documents these are and how to be given
  // them.
  const visibleServices = services.filter((s) => !!s.doc);
  const trainingDoc = docs.find((d) => d.id === TRAINING_DOC_ID);
  if (!dailyDoc && !flyDoc && !trainingDoc && visibleServices.length === 0) return <NotYourDepartment documentId={DAILY_DOC_ID} what="document" />;

  // The service provider agreement: the one on file, or the Service Provider
  // page, which is where it is drafted or the signed copy uploaded.
  const openServiceAgreement = () => {
    const current = agreementStatus(isDemo).record;
    navigate(current ? `/record/${current.id}` : "/licence");
  };

  // The signed Responsibilities of Pest Control document: the seeded signed
  // copy on the Live side, a fresh one started here on the Demo side.
  const openResponsibilities = () => {
    const existing = latestRecord<PestResponsibilitiesData>(PR_DOC_ID, isDemo, "9999-12-31");
    if (existing) {
      navigate(`/record/${existing.id}`);
      return;
    }
    const now = new Date().toISOString();
    const rec: RecordInstance<PestResponsibilitiesData> = {
      id: generateId("resp"),
      documentId: PR_DOC_ID,
      periodKey: generateId("period"),
      dueDate: today,
      status: "In Progress",
      isDemo,
      data: newPestResponsibilitiesData(),
      createdAt: now,
      updatedAt: now,
    };
    recordRepository.upsert(rec as RecordInstance);
    navigate(`/record/${rec.id}`);
  };

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <h1 className="text-2xl">{t("pest.title")}</h1>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/library/pest-control")}>
          <FiBookOpen size={13} /> {t("pest.allDocuments")}
        </button>
      </div>
      <p className="text-muted mb-4">
        The Daily Report, Gurudev Pest Control's service reports (Rat / Mice, Ants & Cockroaches, Fly) and the trend analyses drawn from them —{" "}
        {MONTH_NAMES[month]} {year}
        {isDemo ? " (demo data)" : ""}.
      </p>

      <div className="pest-grid">
        {/* 1. Daily Report */}
        {dailyDoc && (
        <div className="card">
          <div className="card-header">
            <h3 className="text-base font-semibold">
              <FiClipboard size={14} style={{ verticalAlign: -2 }} /> {t("pest.dailyReportTitle")}
            </h3>
            <span className="badge badge-Due">Daily</span>
          </div>
          <div className="card-pad">
            <div className="font-semibold">
              {dailyDoc?.name ?? "Daily Pest Control Monitoring Record"} <span className="text-faint text-xs">{dailyDoc?.formatNo}</span>
            </div>
            <div className="text-sm text-muted mb-3">10 checkpoints every day — door proofing, gaps, fly catchers, rodent traps (with box, location and count when a rodent is trapped).</div>
            <div className="flex items-center gap-2 mb-3 wrap">
              <span className="text-sm">Today, {formatDisplayDate(today)}:</span>
              {todayRecord ? <StatusBadge status={todayRecord.status} /> : <span className="text-faint text-sm">no record</span>}
              {todayRecord?.prepared && todayRecord.status === "In Progress" && <span className="text-xs text-muted">prepared by your assistant — review and submit</span>}
            </div>
            <div className="flex gap-4 wrap text-sm mb-3">
              <span>
                <strong>{daysRecorded}</strong> days recorded
              </span>
              <span className={awaiting ? "text-warning" : ""}>
                <strong>{awaiting}</strong> awaiting submit
              </span>
              <span className={findings ? "text-danger" : ""}>
                <strong>{findings}</strong> findings
              </span>
              <span className={rodentsMonth ? "text-danger" : ""}>
                <strong>{rodentsMonth}</strong> rodents this month
              </span>
            </div>
            <div className="flex gap-2 wrap">
              <button className="btn btn-primary btn-sm" onClick={() => navigate(todayRecord ? `/record/${todayRecord.id}` : `/day/${today}`)}>
                {t("pest.openTodaysRecord")} <FiArrowRight size={12} />
              </button>
              <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/daily")}>
                <FiCalendar size={12} /> {t("pest.monthRegister")}
              </button>
            </div>
          </div>
        </div>
        )}

        {/* 2. Service Reports */}
        {visibleServices.length > 0 && (
        <div className="card">
          <div className="card-header">
            <h3 className="text-base font-semibold">
              <FiTruck size={14} style={{ verticalAlign: -2 }} /> {t("pest.serviceReportsTitle")}
            </h3>
            <span className="badge badge-Due">Fortnightly</span>
          </div>
          <div className="card-pad" style={{ paddingTop: 8 }}>
            <div className="text-sm text-muted mb-2">Gurudev Pest Control's visit reports — 4th & 18th of each month, one per service.</div>
            <div className="doc-table">
              <table className="compact">
                <thead>
                  <tr>
                    <th>Service</th>
                    <th>Last visit</th>
                    <th>Next due</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {visibleServices.map((s) => (
                    <tr key={s.slug} className="card-clickable" onClick={() => navigate(`/pest/service/${s.slug}`)}>
                      <td>
                        <div className="font-semibold text-sm">{s.title}</div>
                        <div className="text-xs text-faint">{s.pests}</div>
                      </td>
                      <td className="text-sm">
                        {s.last ? (
                          <span className="flex items-center gap-2 wrap">
                            {formatDisplayDate(s.last.dueDate)} <StatusBadge status={s.last.status} />
                          </span>
                        ) : (
                          <span className="text-faint">—</span>
                        )}
                      </td>
                      <td className="text-sm">{s.next ? formatDisplayDate(s.next) : "—"}</td>
                      <td style={{ textAlign: "right" }}>
                        <button className="btn btn-ghost btn-sm">
                          Open <FiArrowRight size={12} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        )}

        {/* 3. Trend Analysis */}
        {(dailyDoc || flyDoc) && (
        <div className="card">
          <div className="card-header">
            <h3 className="text-base font-semibold">
              <FiTrendingUp size={14} style={{ verticalAlign: -2 }} /> {t("pest.trendAnalysisTitle")}
            </h3>
            <span className="badge badge-Due">Monthly</span>
          </div>
          <div className="card-pad">
            {dailyDoc && (
            <div className="mb-4">
              <div className="font-semibold text-sm">Rodent Catch Report and Trend Analysis</div>
              <div className="text-sm text-muted">
                From checkpoint 7 of the Daily Report — trap box, location and number of rodents, month by month in the company's own layout.{" "}
                <strong className={rodentsYear ? "text-danger" : ""}>{rodentsYear}</strong> rodent{rodentsYear === 1 ? "" : "s"} in {year}, {rodentsMonth} this month.
              </div>
              <button className="btn btn-secondary btn-sm mt-2" onClick={() => navigate("/pest/trend/rodent")}>
                Open <FiArrowRight size={12} />
              </button>
            </div>
            )}
            {dailyDoc && (
            <div className="mb-4">
              <div className="font-semibold text-sm">Lizard Catch Report and Trend Analysis</div>
              <div className="text-sm text-muted">
                The house lizards off the same glue boards, as the service provider reports them each month — the company's own page, transcribed.
              </div>
              <button className="btn btn-secondary btn-sm mt-2" onClick={() => navigate("/pest/trend/lizard")}>
                Open <FiArrowRight size={12} />
              </button>
            </div>
            )}
            {flyDoc && (
            <div>
              <div className="font-semibold text-sm">Flies Catch Report and Trend Analysis</div>
              <div className="text-sm text-muted">
                Gramms collected out of the electric fly killers each month, as reported; below it the fortnightly F/HR/18 inspection of PC-01…PC-13,
                added up per unit. <strong>{fliesYear}</strong> flies counted in {year}, {fliesMonth} this month ({flySeasonLabel(month)}). Next inspection{" "}
                {nextFly ? formatDisplayDate(nextFly) : "—"}.
              </div>
              <button className="btn btn-secondary btn-sm mt-2" onClick={() => navigate("/pest/trend/fly-catcher")}>
                Open <FiArrowRight size={12} />
              </button>
            </div>
            )}
          </div>
        </div>
        )}

        {/* 4. Training & Reference */}
        {trainingDoc && (
        <div className="card">
          <div className="card-header">
            <h3 className="text-base font-semibold">
              <FiAward size={14} style={{ verticalAlign: -2 }} /> {t("pest.trainingReferenceTitle")}
            </h3>
            <span className="badge badge-Due">Yearly / reference</span>
          </div>
          <div className="card-pad">
            <div className="text-sm text-muted mb-3">
              Last training: {lastTraining ? `${formatDisplayDate(lastTraining.data.trainingDate || lastTraining.dueDate)} — ${lastTraining.data.trainingType || "pest control training"}` : "—"}. The
              chemical chart is the reference material behind the service reports; Gurudev Pesticides' Government of Gujarat insecticide licence
              (Form III, MEH/FP1230000675/2023-2024) is on file, exactly as supplied.
            </div>
            <div className="flex gap-2 wrap">
              <button className="btn btn-secondary btn-sm" onClick={() => navigate("/training")}>
                <FiAward size={12} /> Training Records
              </button>
              <button className="btn btn-secondary btn-sm" onClick={() => navigate("/chemical-master")}>
                <FiDroplet size={12} /> Chemical Master
              </button>
              <button className="btn btn-secondary btn-sm" onClick={() => navigate("/licence")}>
                <FiFileText size={12} /> Service Provider Licence
              </button>
              <button className="btn btn-secondary btn-sm" data-action="open-responsibilities" onClick={openResponsibilities}>
                <FiFileText size={12} /> Responsibilities (Site &amp; Provider)
              </button>
              {/* The two-yearly contract: its standing, and the renewal, live
                  on the Service Provider page (engine/serviceAgreement.ts). */}
              <button className="btn btn-secondary btn-sm" data-action="open-service-agreement" onClick={openServiceAgreement}>
                <FiFileText size={12} /> Service Agreement (every 2 years)
              </button>
            </div>
          </div>
        </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// 1. Daily Report — /pest/daily[/{year}/{month0}]

export function DailyMonitoringListPage({ year: initialYear, month: initialMonth }: { year?: number; month?: number }) {
  const { mode, version } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const now = new Date();
  const [year, setYear] = useState(initialYear ?? now.getFullYear());
  const [month, setMonth] = useState(initialMonth ?? now.getMonth());
  // The register (the company's own F/HR/17 layout) is the default; the
  // status list is the app-side view of the same records.
  const [view, setView] = useState<"register" | "list">("register");
  const [showOriginal, setShowOriginal] = useState(false);
  const today = todayISO();
  useEnsureMonth(year, month, version);

  const doc = documentRepository.getById(DAILY_DOC_ID);
  // F/HR/17 is Human Resources' own format, so somebody outside that
  // department who reaches this address by an old bookmark or a link is told
  // whose register it is. Nothing crashed without this guard, which is why
  // it was easy to miss: the records are scoped by the same rule, so the
  // page drew a month nobody had filled in, and an empty register reads as a
  // lapse in the plant's paperwork rather than as another department's
  // document (REQUIREMENTS §40). The return sits below every hook, so the
  // order of hooks never changes between renders.
  if (!doc) return <NotYourDepartment documentId={DAILY_DOC_ID} what="register" />;
  const master = masterRepository.get();
  const records = recordRepository.query({ documentId: DAILY_DOC_ID, isDemo, ...monthRange(year, month) }) as RecordInstance<DailyPestMonitoringData>[];
  const byDate = new Map(records.map((r) => [r.dueDate, r]));
  const dim = daysInMonth(year, month);
  const todayRecord = byDate.get(today);

  const stats = { recorded: 0, awaiting: 0, findings: 0, rodents: 0, holidays: 0 };
  for (const r of records) {
    if (r.data.isHoliday) {
      stats.holidays += 1;
      continue;
    }
    if (DONE_STATUSES.has(r.status)) stats.recorded += 1;
    else if (compareISO(r.dueDate, today) <= 0) stats.awaiting += 1;
    stats.findings += countFindings(master.checkpoints, r.data.checkpoints);
    if (r.data.checkpoints[7]?.value === "Yes") stats.rodents += Math.max(totalRodents(r.data.rodentCatches), r.data.rodentCatches?.length ? 0 : 1);
  }

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <div>
          <h1 className="text-2xl mb-1">{t("pest.dailyReportTitle")} — {t("nav.dailyPestMonitoring")}</h1>
          {doc && <DocMeta doc={doc} />}
        </div>
        <div className="flex gap-2 wrap">
          <YearSelect value={year} onChange={setYear} />
          <MonthSelect value={month} onChange={setMonth} />
        </div>
      </div>
      <p className="text-muted mb-4">
        One record per day — the assistant prepares each one before you arrive; you review, correct anything only a person could know, and Submit. Shown below in
        the company's own F/HR/17 layout: the three-page monthly register (instructions and check points; dates 1–19; dates 20–31 and the Summary of Actions).
      </p>

      <div className="flex gap-3 wrap mb-4">
        <div className="stat-tile">
          <div className="stat-value">{stats.recorded}</div>
          <div className="stat-label">{t("pest.daysRecorded", { month: MONTH_NAMES[month] })}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value" style={stats.awaiting ? { color: "var(--color-warning)" } : undefined}>
            {stats.awaiting}
          </div>
          <div className="stat-label">{t("pest.awaitingSubmit")}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value" style={stats.findings ? { color: "var(--color-danger)" } : undefined}>
            {stats.findings}
          </div>
          <div className="stat-label">{t("pest.findingsFlagged")}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value" style={stats.rodents ? { color: "var(--color-danger)" } : { color: "var(--color-success)" }}>
            {stats.rodents}
          </div>
          <div className="stat-label">{t("pest.rodentsTrapped")}</div>
        </div>
      </div>

      <div className="flex gap-2 wrap mb-3">
        <button className="btn btn-primary btn-sm" onClick={() => navigate(todayRecord ? `/record/${todayRecord.id}` : `/day/${today}`)}>
          {t("pest.openTodaysRecord")} <FiArrowRight size={12} />
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate(`/reports/${year}/${month}/daily`)}>
          Daily Monitoring Summary report
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/trend/rodent")}>
          <FiTrendingUp size={12} /> Rodent Catch Trend
        </button>
        <DownloadDocumentButton doc={doc} dateISO={`${year}-${String(month + 1).padStart(2, "0")}-01`} />
        <button className="btn btn-secondary btn-sm" onClick={() => printDocument()}>
          <FiPrinter size={12} /> {t("pest.printRegister")}
        </button>
      </div>

      <div className="flex items-center justify-between wrap gap-2 mb-2 no-print">
        <div className="pill-tabs">
          <div className={`pill-tab ${view === "register" ? "active" : ""}`} {...pressable(() => setView("register"), view === "register")}>
            {t("pest.registerView")}
          </div>
          <div className={`pill-tab ${view === "list" ? "active" : ""}`} {...pressable(() => setView("list"), view === "list")}>
            {t("pest.statusListView")}
          </div>
        </div>
        <button className="btn btn-ghost btn-sm" onClick={() => setShowOriginal((s) => !s)}>
          {showOriginal ? t("pest.hideOriginal") : t("pest.showOriginal")}
        </button>
      </div>

      {showOriginal && (
        <div className="card mb-3 no-print">
          <div className="card-pad">
            <div className="text-xs text-muted mb-2">"Daily pest control monitoring record .pdf" — the three printed pages this register reproduces, shown unaltered.</div>
            <div className="register-original">
              {FHR17_ORIGINAL_PAGES.map((src, i) => (
                <img key={src} src={src} alt={`F/HR/17 blank format, page ${i + 1} of 3`} />
              ))}
            </div>
          </div>
        </div>
      )}

      {view === "register" && <DailyRegisterSheet year={year} month={month} isDemo={isDemo} onOpenDay={(r) => navigate(`/record/${r.id}`)} />}

      {view === "list" && (
      // The list is a document in its own right once it is on paper, so it
      // prints with the register's own header block — company name, title,
      // Format No. / Rev No. and the month it covers (REQUIREMENTS §38). A
      // bare grid with no heading is what made a printout look unfinished.
      <div className="register-sheet" data-print-doc>
        <section className="register-page">
        {doc && <DocumentHeader doc={doc} extraTitle={`STATUS LIST — ${MONTH_NAMES[month].toUpperCase()} ${year}`} dateLabel={`${MONTH_NAMES[month]} ${year}`} />}
        <div className="doc-table" style={{ border: "none" }}>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Status</th>
              <th>Findings</th>
              <th>Rodents (box · location)</th>
              <th>Checker</th>
              <th>Time</th>
              <th className="no-print"></th>
            </tr>
          </thead>
          <tbody>
            {Array.from({ length: dim }, (_, i) => i + 1).map((d) => {
              const dateISO = `${year}-${pad2(month + 1)}-${pad2(d)}`;
              const r = byDate.get(dateISO);
              const isToday = dateISO === today;
              const findings = r && !r.data.isHoliday ? countFindings(master.checkpoints, r.data.checkpoints) : 0;
              const rodents = rodentCellFor(r);
              const weekday = WEEKDAY_NAMES[new Date(year, month, d).getDay()];
              return (
                <tr key={d} className={`${r ? "card-clickable" : ""} ${isToday ? "is-today" : ""}`} onClick={r ? () => navigate(`/record/${r.id}`) : undefined}>
                  <td>
                    <span className="font-semibold">{d}</span> <span className="text-faint text-xs">{weekday}</span>
                    {isToday && <span className="text-xs text-muted"> · today</span>}
                  </td>
                  <td>
                    {r?.data.isHoliday ? <span className="badge badge-Scheduled">HOLIDAY</span> : r ? <StatusBadge status={r.status} /> : <span className="text-faint">—</span>}
                    {r?.isDemo && <DemoTag />}
                  </td>
                  <td>{r?.data.isHoliday ? "—" : findings > 0 ? <span className="text-danger font-semibold">{findings}</span> : r ? "0" : "—"}</td>
                  <td className={`text-sm ${rodents ? "text-danger" : "text-faint"}`}>{rodents || "—"}</td>
                  <td className="text-sm">{r?.data.checker || "—"}</td>
                  <td className="text-sm">{r?.data.timeOfChecking || "—"}</td>
                  <td className="no-print" style={{ textAlign: "right" }}>{r && <button className="btn btn-ghost btn-sm">Open</button>}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        </div>
        </section>
      </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// 2. Service Reports — /pest/service/{rodent|general|fly}[/{year}]

export function ServiceReportListPage({ slug, year: initialYear }: { slug: string; year?: number }) {
  const { mode, version } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const now = new Date();
  const [year, setYear] = useState(initialYear ?? now.getFullYear());
  // Month of the F/HR/18 register shown on the Fly Control page.
  const [registerMonth, setRegisterMonth] = useState(now.getMonth());
  const today = todayISO();
  useEnsureMonth(now.getFullYear(), now.getMonth(), version);

  const service = PEST_SERVICES[slug];
  const doc = service ? documentRepository.getById(service.docId) : undefined;
  const master = masterRepository.get();

  // An address nobody recognises and a report outside the viewer's departments
  // are two different things, and only the first is a wrong address: the
  // provider's visit reports are filed with Human Resources' pest control
  // file, so when the plant still holds the definition and only the scoped
  // lookup came back empty, this is a department refusal, and "Unknown
  // service report" would send somebody hunting a broken link that isn't
  // there (REQUIREMENTS §40). The unscoped lookup is what tells the two
  // apart; the empty state below is kept for a slug that really is unknown.
  if (service && !doc) {
    const unscoped = documentRepository.getByIdUnscoped(service.docId);
    if (unscoped) return <NotYourDepartment documentId={unscoped.id} formatNo={unscoped.formatNo} what="report" />;
  }

  if (!service || !doc) {
    return (
      <div className="empty-state">
        <h2 className="text-xl mb-2">Unknown service report</h2>
        <p>Choose Rat / Mice, Ants & Cockroaches or Fly Control from the Pest Control module.</p>
      </div>
    );
  }

  const records = (recordRepository.query({ documentId: doc.id, isDemo, fromDate: `${year}-01-01`, toDate: `${year}-12-31` }) as RecordInstance<ServiceReportData>[])
    .slice()
    .sort((a, b) => compareISO(b.dueDate, a.dueDate));
  const areas = master.areas.filter((a) => a.context === `service-report:${doc.variantKey}`);
  const materials = Array.from(new Set(areas.map((a) => fixedMaterialForServiceArea(doc.variantKey, a.name).materialName).filter(Boolean)));
  const next = nextDueDate(doc, today);
  const last = latestRecord<ServiceReportData>(doc.id, isDemo, today);
  const completed = records.filter((r) => DONE_STATUSES.has(r.status)).length;

  const summary = (r: RecordInstance<ServiceReportData>) => {
    const mats = Array.from(new Set(r.data.lines.map((l) => l.materialName).filter(Boolean))).join(" / ");
    const remarks = Array.from(new Set(r.data.lines.map((l) => l.remarks.trim()).filter((x) => x && x !== "-")));
    return { mats, remarks: remarks.slice(0, 2).join("; ") + (remarks.length > 2 ? "…" : "") };
  };

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <div>
          <h1 className="text-2xl mb-1">Service Report — {service.title}</h1>
          <DocMeta doc={doc} />
        </div>
        <YearSelect value={year} onChange={setYear} />
      </div>
      <p className="text-muted mb-4">{doc.description}</p>

      <div className="flex gap-3 wrap mb-4">
        <div className="stat-tile">
          <div className="stat-value" style={{ fontSize: 18 }}>
            {next ? formatDisplayDate(next) : "—"}
          </div>
          <div className="stat-label">{t("pest.nextVisitDue")}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value" style={{ fontSize: 18 }}>
            {last ? formatDisplayDate(last.dueDate) : "—"}
          </div>
          <div className="stat-label">Last visit{last ? ` · ${last.status}` : ""}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value">{completed}</div>
          <div className="stat-label">{t("pest.visitsCompleted", { year })}</div>
        </div>
        <div className="stat-tile">
          <div className="stat-value" style={{ fontSize: 15, lineHeight: 1.3 }}>
            {materials.join(" / ") || "—"}
          </div>
          <div className="stat-label">
            Material · {areas.length} fixed areas · {service.pests}
          </div>
        </div>
      </div>

      <div className="flex gap-2 wrap mb-3">
        {last && (
          <button className="btn btn-primary btn-sm" onClick={() => navigate(`/record/${last.id}`)}>
            {t("pest.openLatestVisit")} <FiArrowRight size={12} />
          </button>
        )}
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/chemical-master")}>
          <FiDroplet size={12} /> Chemical Master
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate(`/reports/${now.getFullYear()}/${now.getMonth()}/chemical`)}>
          Chemical Usage report
        </button>
      </div>

      {/* On paper this is the service report's own visit register for the year,
          so it carries the document's header block (REQUIREMENTS §38). */}
      <div className="register-sheet" data-print-doc>
        <section className="register-page">
        <DocumentHeader doc={doc} extraTitle={`VISIT REGISTER ${year}`} dateLabel={String(year)} />
        {/* data-table: a stable hook, since this page now also carries the
            company-format sheets, which are tables too. */}
        <div className="doc-table" style={{ border: "none" }}>
        <table data-table="visits">
          <thead>
            <tr>
              <th>Service date</th>
              <th>Status</th>
              <th>Technician</th>
              <th>Customer's sign</th>
              <th>Areas</th>
              <th>Material</th>
              <th>Remarks</th>
              <th className="no-print"></th>
            </tr>
          </thead>
          <tbody>
            {records.length === 0 && (
              <tr>
                <td colSpan={8} className="text-muted text-center" style={{ padding: 24 }}>
                  No {service.title} visits recorded in {year}{isDemo ? " (demo)" : ""} yet — visits are scheduled on the 4th and 18th of each month.
                </td>
              </tr>
            )}
            {records.map((r) => {
              const s = summary(r);
              return (
                <tr key={r.id} className={`card-clickable ${r.dueDate === today ? "is-today" : ""}`} onClick={() => navigate(`/record/${r.id}`)}>
                  <td className="font-semibold">{formatDisplayDate(r.dueDate)}</td>
                  <td>
                    <StatusBadge status={r.status} />
                    {r.isDemo && <DemoTag />}
                  </td>
                  <td className="text-sm">{r.data.technicianSign || "—"}</td>
                  <td className="text-sm">{r.data.customerSign || <span className="text-faint">—</span>}</td>
                  <td className="text-sm">{r.data.lines.length}</td>
                  <td className="text-sm">{s.mats || "—"}</td>
                  <td className="text-sm">{s.remarks || <span className="text-faint">—</span>}</td>
                  <td className="no-print" style={{ textAlign: "right" }}>
                    <button className="btn btn-ghost btn-sm">Open</button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        </div>
        </section>
      </div>

      {/* The company's own formats that go with this service, filled from the
          records: the F/HR/18 fly catcher register beside Fly Control, and the
          Rodent Catch Report and Trend Analysis beside Rat / Mice. Same
          components (and the same data) as Pest Control > Trend Analysis. */}
      {slug === "fly" && (
        <div className="mt-6" data-section="fhr18">
          <div className="flex items-center justify-between wrap gap-2 mb-1">
            <h2 className="text-lg">{t("pest.fhr18SectionTitle")}</h2>
            {/* The register's Month & Year (the year is the page's own). Add
                visit / Edit register / Print sit on the register itself. */}
            <div className="flex gap-2 no-print">
              <YearSelect value={year} onChange={setYear} />
              <MonthSelect value={registerMonth} onChange={setRegisterMonth} />
            </div>
          </div>
          <FlyCatcherRegisterSheet year={year} month={registerMonth} isDemo={isDemo} onOpenVisit={(r) => navigate(`/record/${r.id}`)} allowEdit />
        </div>
      )}
      {slug === "rodent" && (
        <div className="mt-6" data-section="rodent-trend">
          <RodentTrendReport isDemo={isDemo} year={year} />
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// 3a. Trend Analysis — Rodent Catch — /pest/trend/rodent[/{year}]

export function RodentTrendPage({ year: initialYear }: { year?: number }) {
  const { mode } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const [year, setYear] = useState(initialYear ?? new Date().getFullYear());
  const doc = documentRepository.getById(DAILY_DOC_ID);
  // The trend is counted off F/HR/17's own daily records, which are Human
  // Resources', so for anybody else this page could only ever draw an empty
  // chart and a table of zeros below a caption quoting a format number that
  // came out blank. Degrading quietly like that looks like a plant with no
  // rodents; the refusal says whose document it is instead
  // (REQUIREMENTS §40).
  if (!doc) return <NotYourDepartment documentId={DAILY_DOC_ID} what="report" />;

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <div>
          <h1 className="text-2xl mb-1">{t("pest.trendAnalysisTitle")} — {t("nav.rodentTrend")}</h1>
          <div className="text-xs text-muted">
            Counted from checkpoint 7 of the Daily Report ({doc?.formatNo}) — trap box, location and number of rodents on each day's record.
          </div>
        </div>
        <YearSelect value={year} onChange={setYear} />
      </div>
      <div className="flex gap-2 wrap mb-4 mt-3">
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/daily")}>
          <FiClipboard size={12} /> Daily Report register
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/service/rodent")}>
          <FiTruck size={12} /> Rat / Mice service reports
        </button>
      </div>
      <RodentTrendReport isDemo={isDemo} year={year} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// 3b. Trend Analysis — Lizard Catch Report — /pest/trend/lizard[/{year}]

export function LizardTrendPage({ year: initialYear }: { year?: number }) {
  const { mode } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const [year, setYear] = useState(initialYear ?? new Date().getFullYear());
  const doc = documentRepository.getById(DAILY_DOC_ID);
  // The lizards come off the glue boards in F/HR/17's own Roda-boxes, so this
  // report belongs to the same document — and to the same department. Outside
  // it the refusal names the owner rather than drawing somebody else's trend
  // (REQUIREMENTS §40).
  if (!doc) return <NotYourDepartment documentId={DAILY_DOC_ID} what="report" />;

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <div>
          <h1 className="text-2xl mb-1">{t("pest.trendAnalysisTitle")} — {t("nav.lizardTrend")}</h1>
          <div className="text-xs text-muted">
            As the service provider reports it each month, transcribed from the company's own Lizard Catch Report and Trend Analysis — the same
            glue boards in the same Roda-boxes as the rodents, which {doc?.formatNo} has no column for.
          </div>
        </div>
        <YearSelect value={year} onChange={setYear} />
      </div>
      <div className="flex gap-2 wrap mb-4 mt-3">
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/trend/rodent")}>
          <FiTrendingUp size={12} /> Rodent Catch Report
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/service/rodent")}>
          <FiTruck size={12} /> Rat / Mice service reports
        </button>
      </div>
      <LizardTrendReport isDemo={isDemo} year={year} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// 3c. Trend Analysis — Fly Catcher Infestation — /pest/trend/fly-catcher[/{year}]

export function FlyCatcherTrendPage({ year: initialYear }: { year?: number }) {
  const { mode, version } = useAppStore();
  const t = useT();
  const { navigate } = useRouter();
  const isDemo = mode === "demo";
  const now = new Date();
  const [year, setYear] = useState(initialYear ?? now.getFullYear());
  const [month, setMonth] = useState(now.getMonth());
  // The register (the company's own F/HR/18 layout) is the default, as on the
  // Daily Report page; the trend and the visit list are views of the same
  // records.
  const [view, setView] = useState<"register" | "trend" | "list">("register");
  const today = todayISO();
  useEnsureMonth(now.getFullYear(), now.getMonth(), version);

  const doc = documentRepository.getById(FLY_DOC_ID);
  // The register, the trend and the visit list here are all F/HR/18, Human
  // Resources' own format, so this whole page is one document a viewer may
  // either see or not: outside HR it is told whose register it is rather
  // than shown thirteen empty fly catcher units and a trend of nothing
  // (REQUIREMENTS §40).
  if (!doc) return <NotYourDepartment documentId={FLY_DOC_ID} what="register" />;
  const records = (recordRepository.query({ documentId: FLY_DOC_ID, isDemo, fromDate: `${year}-01-01`, toDate: `${year}-12-31` }) as RecordInstance<FlyCatcherData>[])
    .slice()
    .sort((a, b) => compareISO(b.dueDate, a.dueDate));
  const next = doc ? nextDueDate(doc, today) : null;
  const latest = latestRecord<FlyCatcherData>(FLY_DOC_ID, isDemo, today);

  const rowStats = (r: RecordInstance<FlyCatcherData>) => {
    let total = 0;
    let top: { pcId: string; n: number } | null = null;
    for (const e of r.data.entries) {
      const n = Number(e.catchCountApprox) || 0;
      total += n;
      if (!top || n > top.n) top = { pcId: e.pcId, n };
    }
    return { total, top, cleaning: r.data.entries.find((e) => e.cleaningDoneBy)?.cleaningDoneBy ?? "", verified: r.data.entries.find((e) => e.verifiedBy)?.verifiedBy ?? "" };
  };

  return (
    <div className={isDemo ? "demo-watermark" : ""}>
      <div className="flex items-center justify-between mb-1 wrap gap-3">
        <div>
          <h1 className="text-2xl mb-1">{t("pest.trendAnalysisTitle")} — {t("nav.flyCatcherInfestation")}</h1>
          {doc && <DocMeta doc={doc} />}
        </div>
        <div className="flex gap-2 wrap">
          <YearSelect value={year} onChange={setYear} />
          <MonthSelect value={month} onChange={setMonth} />
        </div>
      </div>
      <p className="text-muted mb-3">
        Every fortnight the 13 fly catcher units are inspected and cleaned and the flies on each glue board counted (F/HR/18). Those counts, added up per unit and per month, are the
        infestation trend — {flySeasonLabel(month)} in {MONTH_NAMES[month]}. Next inspection {next ? formatDisplayDate(next) : "—"}.
      </p>
      <div className="flex gap-2 wrap mb-4">
        {latest && (
          <button className="btn btn-primary btn-sm" onClick={() => navigate(`/record/${latest.id}`)}>
            Open latest inspection <FiArrowRight size={12} />
          </button>
        )}
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/service/fly")}>
          <FiTruck size={12} /> Fly Control service reports
        </button>
        <button className="btn btn-secondary btn-sm" onClick={() => navigate("/pest/daily")}>
          <FiClipboard size={12} /> Daily Report (checkpoints 3 & 10)
        </button>
      </div>

      <div className="flex items-center justify-between wrap gap-2 mb-2 no-print">
        <div className="pill-tabs">
          <div className={`pill-tab ${view === "register" ? "active" : ""}`} data-view="register" {...pressable(() => setView("register"), view === "register")}>
            {t("pest.fhr18RegisterView")}
          </div>
          <div className={`pill-tab ${view === "trend" ? "active" : ""}`} data-view="trend" {...pressable(() => setView("trend"), view === "trend")}>
            {t("pest.trendView")}
          </div>
          <div className={`pill-tab ${view === "list" ? "active" : ""}`} data-view="list" {...pressable(() => setView("list"), view === "list")}>
            {t("pest.visitListView")}
          </div>
        </div>
      </div>

      {/* The Month & Year chosen above: Add visit / Edit register / Print sit on the register itself. */}
      {view === "register" && <FlyCatcherRegisterSheet year={year} month={month} isDemo={isDemo} onOpenVisit={(r) => navigate(`/record/${r.id}`)} allowEdit />}

      {view === "trend" && <FlyCatcherTrendReport isDemo={isDemo} year={year} month={month} />}

      {view === "list" && (
      // The year's inspections as a document: the F/HR/18 header block, then
      // the list (REQUIREMENTS §38).
      <div className="register-sheet" data-print-doc>
        <section className="register-page">
          {doc && <DocumentHeader doc={doc} extraTitle={`INSPECTION & CLEANING RECORDS ${year}`} dateLabel={String(year)} />}
          <h3 className="text-lg no-print" style={{ marginTop: 10 }}>
            <FiActivity size={14} style={{ verticalAlign: -2 }} /> Inspection & cleaning records — {year}
          </h3>
        <div className="doc-table" style={{ border: "none" }}>
          <table>
            <thead>
              <tr>
                <th>Service date</th>
                <th>Status</th>
                <th>Flies (all units)</th>
                <th>Busiest unit</th>
                <th>Cleaning done by</th>
                <th>Verified by</th>
                <th className="no-print"></th>
              </tr>
            </thead>
            <tbody>
              {records.length === 0 && (
                <tr>
                  <td colSpan={7} className="text-muted text-center" style={{ padding: 24 }}>
                    No fly catcher inspections recorded in {year}{isDemo ? " (demo)" : ""} yet — inspections fall on the 3rd and 17th of each month.
                  </td>
                </tr>
              )}
              {records.map((r) => {
                const s = rowStats(r);
                return (
                  <tr key={r.id} className={`card-clickable ${r.dueDate === today ? "is-today" : ""}`} onClick={() => navigate(`/record/${r.id}`)}>
                    <td className="font-semibold">{formatDisplayDate(r.dueDate)}</td>
                    <td>
                      <StatusBadge status={r.status} />
                      {r.isDemo && <DemoTag />}
                    </td>
                    <td className={`text-sm ${s.total ? "font-semibold" : "text-faint"}`}>{s.total}</td>
                    <td className="text-sm">{s.top && s.top.n > 0 ? `${s.top.pcId} (${s.top.n})` : "—"}</td>
                    <td className="text-sm">{s.cleaning || "—"}</td>
                    <td className="text-sm">{s.verified || "—"}</td>
                    <td className="no-print" style={{ textAlign: "right" }}>
                      <button className="btn btn-ghost btn-sm">Open</button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        </section>
      </div>
      )}
    </div>
  );
}
