// GENERATED by tools/pest_pattern.py — do not edit by hand; edit the
// Python and re-run it. See that file for how each number was derived and
// how each pattern was calibrated against the company's own documents
// (Rodent Catch Report: 0 rodents in 2024, 2 in 2025, 0 through Jun-2026;
// Fly Catcher register: August-2026 specimen, 0-3 flies per unit per visit).

// ===================== RODENT (F/HR/17, checkpoints 7/8/9) =====================

// Probability that a given calendar day has a rodent catch, by month
// (Jan..Dec). Seasonal — peaks in the monsoon, ~5 catch days a year.
export const RODENT_MONTHLY_RATE: number[] = [0.003, 0.0014, 0.003, 0.0075, 0.0137, 0.0199, 0.0244, 0.026, 0.0244, 0.0199, 0.0137, 0.0075];

// The 16 Rodent Control Service areas with catch weights and the numbered
// trap boxes (RB-01..RB-100) each one owns.
export interface RodentLocationSpec {
  area: string;
  weight: number;
  boxFrom: number;
  boxTo: number;
}
export const RODENT_LOCATIONS: RodentLocationSpec[] = [
  {
    "area": "Printing machine - Ground Floor",
    "weight": 0.474,
    "boxFrom": 1,
    "boxTo": 6
  },
  {
    "area": "Anilox cleaning area - Ground floor",
    "weight": 0.375,
    "boxFrom": 7,
    "boxTo": 12
  },
  {
    "area": "Store - Label stock & PVC / PET Films - Ground floor",
    "weight": 1.295,
    "boxFrom": 13,
    "boxTo": 18
  },
  {
    "area": "Ink store - Ground floor",
    "weight": 0.513,
    "boxFrom": 19,
    "boxTo": 24
  },
  {
    "area": "RM Inward & FG Dispatch room - Ground floor",
    "weight": 1.746,
    "boxFrom": 25,
    "boxTo": 30
  },
  {
    "area": "Walkways - Ground Floor",
    "weight": 0.812,
    "boxFrom": 31,
    "boxTo": 36
  },
  {
    "area": "First floor - Walkways",
    "weight": 0.498,
    "boxFrom": 37,
    "boxTo": 42
  },
  {
    "area": "First floor - Slitting & Packing",
    "weight": 0.657,
    "boxFrom": 43,
    "boxTo": 48
  },
  {
    "area": "First floor - Offline punching & QC Inspection",
    "weight": 0.548,
    "boxFrom": 49,
    "boxTo": 54
  },
  {
    "area": "First floor - Printing machine",
    "weight": 0.393,
    "boxFrom": 55,
    "boxTo": 60
  },
  {
    "area": "First floor - Ink Kitchen",
    "weight": 0.429,
    "boxFrom": 61,
    "boxTo": 66
  },
  {
    "area": "First floor - Shrink Sleeve production",
    "weight": 0.43,
    "boxFrom": 67,
    "boxTo": 72
  },
  {
    "area": "First floor - Intermediate Store",
    "weight": 0.85,
    "boxFrom": 73,
    "boxTo": 78
  },
  {
    "area": "Change room & Locker room - Ground Floor",
    "weight": 0.736,
    "boxFrom": 79,
    "boxTo": 84
  },
  {
    "area": "QC Lab",
    "weight": 0.312,
    "boxFrom": 85,
    "boxTo": 90
  },
  {
    "area": "Canteen",
    "weight": 1.907,
    "boxFrom": 91,
    "boxTo": 100
  }
];

// Rodents per catch day.
export const RODENT_COUNT_DIST: { count: number; p: number }[] = [{"count": 1, "p": 0.72}, {"count": 2, "p": 0.22}, {"count": 3, "p": 0.06}];
export const RODENT_SECOND_LOCATION_P = 0.15;
export const RODENT_CAKE_BITING_P = 0.35;
export const RODENT_CAKE_BITING_ALONE_P = 0.012;
export const RODENT_DEAD_P = 0.2;

// The company's own "Rodent Catch Report and Trend Analysis" — Source:
// Trapped on Glue boards in Roda-boxes; Unit: Number; Target Pest: Rodents.
// null = month not yet reported on the source page.
//
// TWO ISSUES OF THE SAME REPORT have been supplied, and they agree on every
// cell both of them fill. This is the later one ("Kapila mam department
// reports .pdf"), which completes 2025 and carries Jan-Jun 2026;
// "GP-3 Trend Analysis - 2025.pdf" (13-Sep-2026) is the October-2025 snapshot
// and leaves Nov/Dec 2025 and the Total blank. The complete row is kept so the
// company's later figures are not discarded — REQUIREMENTS open question 10.
// The lizard and flies pages of that same file, which have no earlier issue,
// are in data/seed/trendReports.ts.
export interface RodentHistoryRow {
  year: number;
  months: (number | null)[];
  total: number | null;
}
export const RODENT_HISTORY_REPORTED: RodentHistoryRow[] = [
  {
    "year": 2024,
    "months": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "total": 0
  },
  {
    "year": 2025,
    "months": [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "total": 2
  },
  {
    "year": 2026,
    "months": [
      0,
      0,
      0,
      0,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "total": null
  }
];
export const RODENT_HISTORY_SOURCE = "Kapila mam department reports .pdf, page 1 — Rodent Catch Report and Trend Analysis";
export const RODENT_REPORT_MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];

// ===================== FLY CATCHERS (F/HR/18, PC-01..PC-13) =====================

// Relative fly activity by month (Jan..Dec), 1.0 = the August peak.
export const FLY_MONTHLY_FACTOR: number[] = [0.394, 0.35, 0.394, 0.513, 0.675, 0.838, 0.956, 1.0, 0.956, 0.838, 0.675, 0.513];

// Mean flies caught per unit per fortnightly visit in the peak month.
export const FLY_UNIT_BASE: Record<string, number> = {
  "PC-01": 1.1,
  "PC-02": 0.7,
  "PC-03": 1.6,
  "PC-04": 1.0,
  "PC-05": 1.3,
  "PC-06": 1.0,
  "PC-07": 1.0,
  "PC-08": 0.7,
  "PC-09": 0.95,
  "PC-10": 1.3,
  "PC-11": 1.0,
  "PC-12": 1.3,
  "PC-13": 1.0
};

// The August-2026 specimen the fly pattern was calibrated to: per unit,
// [visit on 03-Aug-26, visit on 17-Aug-26].
export const FLY_SPECIMEN_AUG_2026: Record<string, [number, number]> = {
  "PC-01": [
    1,
    1
  ],
  "PC-02": [
    0,
    1
  ],
  "PC-03": [
    2,
    2
  ],
  "PC-04": [
    1,
    1
  ],
  "PC-05": [
    3,
    0
  ],
  "PC-06": [
    1,
    1
  ],
  "PC-07": [
    1,
    1
  ],
  "PC-08": [
    0,
    1
  ],
  "PC-09": [
    1,
    0
  ],
  "PC-10": [
    2,
    1
  ],
  "PC-11": [
    2,
    0
  ],
  "PC-12": [
    1,
    1
  ],
  "PC-13": [
    1,
    0
  ]
};
export const FLY_REPORT_SOURCE = "Kapila mam department reports .pdf, pages 5-6 — Fortnightly Fly Catcher Inspection & Cleaning Record (F/HR/18), August-26";
