// GENERATED by tools/plant_pattern.py — do not edit by hand; edit the Python
// and re-run it. That file documents where every number and every line of
// wording came from.
//
// THE PLANT BEHAVIOUR MODEL. A year of records in which every reading sits on
// nominal, every check point says Yes and every lot is Accepted is an
// obviously synthetic one — the first thing an auditor looks for is the
// exceptions and what was done about them. This model says how often the real
// plant departs from nominal, in what way, and what happens next; the app
// applies it deterministically per calendar date (engine/plantSimulation.ts),
// so the same day always reads the same way on every device.
//
// Calibrated against the company's own documents:
//   * F-QC-30 / F-QC-32 / F-QC-40.C filled specimens (the spread of the
//     readings, and how often they touched the printed limit)
//   * GAP Analysis Report, Dec-2023 (the check-point findings, verbatim)
//   * the photographed lamination sheets of 07-09-26 (jobs, PO series)
//   * Service Report April-2026 (the remarks a technician writes)

// ---------------------------------------------------------------------------
// 1. Process readings

export interface ReadingModel {
  /** Quiet-period sd, in the column's own unit... */
  sigma?: number;
  /** ...or, with no specimen to measure, as a fraction of the half-band. */
  sigmaFraction?: number;
  /** Probability that a day has a drift episode on this reading. */
  episodeRate: number;
  /** How many consecutive readings an episode lasts. */
  minLength: number;
  maxLength: number;
  /** How far the mean walks off during it, in half-bands (>1 goes out of band). */
  minShift: number;
  maxShift: number;
}

/** Keyed "documentId.columnKey"; "documentId.*" applies to every numeric column. */
export const READING_MODELS: Record<string, ReadingModel> = {
  "qc-viscosity.viscosity": {
    "sigma": 0.3,
    "episodeRate": 0.2,
    "minLength": 2,
    "maxLength": 5,
    "minShift": 0.75,
    "maxShift": 1.35
  },
  "qc-temperature.*": {
    "sigma": 0.62,
    "episodeRate": 0.07,
    "minLength": 1,
    "maxLength": 2,
    "minShift": 0.6,
    "maxShift": 1.2
  },
  "qc-adhesive-mixing.viscosity": {
    "sigma": 0.16,
    "episodeRate": 0.05,
    "minLength": 1,
    "maxLength": 1,
    "minShift": 0.9,
    "maxShift": 1.5
  }
};

export const DEFAULT_READING_MODEL: ReadingModel = {
  "sigmaFraction": 0.22,
  "episodeRate": 0.02,
  "minLength": 1,
  "maxLength": 1,
  "minShift": 0.5,
  "maxShift": 1.0
};

export interface ExcursionRemark { remark: string; action: string; }

/** What gets written in the Remark column when a reading goes out, per document. */
export const EXCURSION_REMARKS: Record<string, ExcursionRemark[]> = {
  "qc-viscosity": [
    {
      "remark": "Viscosity high — ethyl acetate added and re-circulated; re-checked after 15 min.",
      "action": "Solvent topped up; reading back within 20.0 +/- 1.0 at the next hour."
    },
    {
      "remark": "Viscosity low — fresh adhesive added to the pot; re-checked.",
      "action": "Mix corrected; next hourly reading in band."
    },
    {
      "remark": "Reading taken while the pot was being topped up — re-checked and in band.",
      "action": "Re-checked after mixing; within specification."
    }
  ],
  "qc-temperature": [
    {
      "remark": "Hot room door found open by material movement; closed and re-checked.",
      "action": "Door closed; temperature recovered at the next reading."
    },
    {
      "remark": "Heater cut-out tripped; reset by maintenance.",
      "action": "Reset and monitored for the rest of the shift."
    }
  ],
  "qc-adhesive-mixing": [
    {
      "remark": "Fresh adhesive drum opened — viscosity adjusted before use.",
      "action": "Batch re-mixed and re-checked before release to the machine."
    },
    {
      "remark": "Ethyl acetate quantity corrected after weighing check.",
      "action": "Batch re-mixed; second reading in band."
    }
  ]
};

// ---------------------------------------------------------------------------
// 2. Daily Pest Control Monitoring (F/HR/17) — the check points that fail.
// Wording is the company's own, from the Dec-2023 GAP Analysis Report.

export interface CheckpointIssue {
  description: string;
  action: string;
  remarks: string;
}

export interface CheckpointIssueModel {
  /** Probability that this check point is flagged on a given working day. */
  rate: number;
  issues: CheckpointIssue[];
}

export const CHECKPOINT_ISSUES: Record<number, CheckpointIssueModel> = {
  "1": {
    "rate": 0.012,
    "issues": [
      {
        "description": "Self-closer of the RM inward door not closing fully; door standing open.",
        "action": "Door closer adjusted by maintenance and re-checked at the end of the shift.",
        "remarks": "Verified closing properly."
      },
      {
        "description": "PVC strip curtain at the dispatch shutter torn — three strips missing.",
        "action": "Damaged strips replaced from stock the same day.",
        "remarks": "Ref. GAP finding: no PVC strip curtain at RM inward shutter."
      }
    ]
  },
  "2": {
    "rate": 0.01,
    "issues": [
      {
        "description": "Gap observed at the utility area opening (birds / flying insects can enter).",
        "action": "Maintenance informed; opening closed with net / screen.",
        "remarks": "Ref. GAP finding 1 (Dec-2023)."
      },
      {
        "description": "Cable entry point above the ink store not sealed.",
        "action": "Sealed with cement mortar; re-checked next day.",
        "remarks": ""
      }
    ]
  },
  "3": {
    "rate": 0.014,
    "issues": [
      {
        "description": "Fly killer machine PC-04 found switched off at the time of checking.",
        "action": "Machine switched on; shift in-charge briefed to keep it on round the clock.",
        "remarks": "Ref. GAP finding: fly killer machine turned off at inspection."
      },
      {
        "description": "One tube light of PC-07 not glowing.",
        "action": "Tube replaced the same day; unit re-checked and working.",
        "remarks": ""
      }
    ]
  },
  "5": {
    "rate": 0.008,
    "issues": [
      {
        "description": "RBS numbering not legible on two rodent boxes near the canteen.",
        "action": "Numbering re-painted on the wall as per the pest control layout.",
        "remarks": "Ref. GAP finding 2 (Dec-2023)."
      }
    ]
  },
  "6": {
    "rate": 0.01,
    "issues": [
      {
        "description": "Rodent box displaced during floor cleaning — found away from its marked position.",
        "action": "Box repositioned as per the pest control layout; housekeeping briefed.",
        "remarks": ""
      },
      {
        "description": "Material stacked against the wall in the store, blocking two rodent boxes.",
        "action": "Material re-stacked away from the wall; boxes accessible again.",
        "remarks": "Ref. GAP finding 3 (Dec-2023) — materials stored haphazardly."
      }
    ]
  }
};

// ---------------------------------------------------------------------------
// 3. QC inspection records — how lots are dispositioned.

export interface Weighted<T> { value: T; weight: number; }

export interface LotDecisionSpec { status: string; weight: number; reason: string; }

export const LOT_DECISIONS: LotDecisionSpec[] = [
  {
    "status": "Accepted",
    "weight": 0.93,
    "reason": ""
  },
  {
    "status": "Accepted on Deviation",
    "weight": 0.045,
    "reason": "DEVIATION"
  },
  {
    "status": "Segregation",
    "weight": 0.018,
    "reason": "SEGREGATION"
  },
  {
    "status": "Reject / Scrap",
    "weight": 0.007,
    "reason": "REJECT"
  }
];

/** documentId -> reason kind -> the wording, in that format's own vocabulary. */
export const LOT_REASONS: Record<string, Record<string, string[]>> = {
  "qc-inspection-pouching": {
    "DEVIATION": [
      "Centre seal width 8 mm against 10 mm specified — accepted on deviation with customer's verbal approval; seal strength checked OK.",
      "Pouch height 178 mm against 181 mm specified (-3 mm) — within customer's agreed tolerance, accepted on deviation."
    ],
    "SEGREGATION": [
      "Leak test failed on 4 pouches of the first 50 — lot segregated, 100% leak testing done before dispatch.",
      "Zipper position varying from top on part of the lot — segregated for re-inspection."
    ],
    "REJECT": [
      "Repeated leak at the bottom gusset seal; sealing jaw temperature found low. Lot rejected / scrapped and job re-run after jaw correction."
    ]
  },
  "qc-inspection-slitting": {
    "DEVIATION": [
      "Bond strength 0.240 kg against 0.300 kg specified — accepted on deviation for a non-retort application after QA review.",
      "Slitted roll width 258 mm against 260 mm as per job card — accepted on deviation, within customer tolerance."
    ],
    "SEGREGATION": [
      "Abnormal odour noticed on two rolls — segregated and kept for 48 h airing, re-tested before dispatch."
    ],
    "REJECT": [
      "Bond strength failure across the mother roll (delamination on peel). Lot rejected / scrapped; adhesive batch quarantined."
    ]
  },
  "qc-inspection-printed-film": {
    "DEVIATION": [
      "Colour shade marginally off against the approved draw-down on one deck — accepted on deviation with customer's approval on shade card.",
      "Print registration variation of 0.3 mm on the repeat — accepted on deviation, legibility unaffected."
    ],
    "SEGREGATION": [
      "Ink smudging observed in part of the reel — segregated for re-inspection and partial rewinding."
    ],
    "REJECT": [
      "Misregistration beyond limit and text overlap on the barcode panel; lot rejected / scrapped and reprinted."
    ]
  }
};

/** How much a measured observation moves around the job's own figure, lot to lot (never compounding). */
export const MEASUREMENT_VARIATION = 0.015;

/** F/QC/13 printing grades, and what the form's own rule says to do about them. */
export const GRADE_MIX: Weighted<string>[] = [
  {
    "value": "A",
    "weight": 0.6
  },
  {
    "value": "B",
    "weight": 0.32
  },
  {
    "value": "C",
    "weight": 0.074
  },
  {
    "value": "F",
    "weight": 0.006
  }
];
export const GRADE_DEFECTS: Record<string, string[]> = {
  "A": [
    "-",
    "-",
    "+1"
  ],
  "B": [
    "+2",
    "+2",
    "+3"
  ],
  "C": [
    "+4",
    "+5"
  ],
  "F": [
    "+8",
    "+11"
  ]
};
export const GRADE_ACTIONS: Record<string, string> = {
  "C": "More than one C grade — printing stopped and QA Manager decided how to proceed; job restarted after correction.",
  "F": "F grade — printing stopped immediately as per the grading rule; QA Manager and supervisor informed."
};

// ---------------------------------------------------------------------------
// 4. The jobs that run, so two days never look identical.

export interface JobSpec {
  fgCode: string;
  jobName: string;
  customer: string;
  layer1Type: string;
  layer2Type: string;
  layer1Kg: number;
  layer2Kg: number;
  rollWeight: number;
  okMeters: number;
  lineSpeed: number;
  nipTemp: number;
  runMinutes: number;
}

export const JOB_POOL: JobSpec[] = [
  {
    "fgCode": "7204",
    "jobName": "VP Bedekar Fenugreek Powder",
    "customer": "VP Bedekar",
    "layer1Type": "PET",
    "layer2Type": "MetPET",
    "layer1Kg": 12.0,
    "layer2Kg": 51.5,
    "rollWeight": 69.1,
    "okMeters": 1950,
    "lineSpeed": 81,
    "nipTemp": 65,
    "runMinutes": 50
  },
  {
    "fgCode": "7205",
    "jobName": "VP Bedekar Cumin Powder",
    "customer": "VP Bedekar",
    "layer1Type": "PET",
    "layer2Type": "MetPET",
    "layer1Kg": 12.5,
    "layer2Kg": 51.1,
    "rollWeight": 70.2,
    "okMeters": 1950,
    "lineSpeed": 81,
    "nipTemp": 70,
    "runMinutes": 55
  },
  {
    "fgCode": "7206",
    "jobName": "VP Bedekar Jeshthamadh Powder",
    "customer": "VP Bedekar",
    "layer1Type": "PET",
    "layer2Type": "MetPET",
    "layer1Kg": 18.0,
    "layer2Kg": 51.5,
    "rollWeight": 70.0,
    "okMeters": 1950,
    "lineSpeed": 65,
    "nipTemp": 70,
    "runMinutes": 75
  },
  {
    "fgCode": "7202",
    "jobName": "VP Bedekar Dry Ginger Powder",
    "customer": "VP Bedekar",
    "layer1Type": "PET",
    "layer2Type": "MetPET",
    "layer1Kg": 18.0,
    "layer2Kg": 51.0,
    "rollWeight": 70.0,
    "okMeters": 1950,
    "lineSpeed": 65,
    "nipTemp": 70,
    "runMinutes": 90
  },
  {
    "fgCode": "6766",
    "jobName": "Sweet Karam Gusset",
    "customer": "Sweet Karam",
    "layer1Type": "BOPP",
    "layer2Type": "MetPET",
    "layer1Kg": 14.0,
    "layer2Kg": 48.0,
    "rollWeight": 62.0,
    "okMeters": 1800,
    "lineSpeed": 130,
    "nipTemp": 60,
    "runMinutes": 60
  },
  {
    "fgCode": "5420",
    "jobName": "California Almonds and Whole Cashews",
    "customer": "Gulab Oil And Food",
    "layer1Type": "BOPP",
    "layer2Type": "MetPET",
    "layer1Kg": 16.0,
    "layer2Kg": 52.0,
    "rollWeight": 72.5,
    "okMeters": 2100,
    "lineSpeed": 95,
    "nipTemp": 68,
    "runMinutes": 70
  },
  {
    "fgCode": "5703",
    "jobName": "Gulab Oil Pouch Film",
    "customer": "Gulab Oil And Food",
    "layer1Type": "PET",
    "layer2Type": "LDPE",
    "layer1Kg": 15.0,
    "layer2Kg": 49.5,
    "rollWeight": 68.0,
    "okMeters": 2000,
    "lineSpeed": 88,
    "nipTemp": 66,
    "runMinutes": 65
  }
];

/** PO numbers climb with the calendar, as a real PO series does. */
export const PO_SERIES = {
  "base": 88823,
  "onDate": "2026-09-07",
  "perDay": 6
};

export const JOBS_PER_SHIFT: Weighted<number>[] = [
  {
    "value": 3,
    "weight": 0.22
  },
  {
    "value": 4,
    "weight": 0.4
  },
  {
    "value": 5,
    "weight": 0.3
  },
  {
    "value": 6,
    "weight": 0.08
  }
];

// ---------------------------------------------------------------------------
// 5. How work actually gets signed off.

export const SUBMIT_LAG_DAYS: Weighted<number>[] = [
  {
    "value": 0,
    "weight": 0.82
  },
  {
    "value": 1,
    "weight": 0.14
  },
  {
    "value": 2,
    "weight": 0.04
  }
];
export const VERIFY_LAG_DAYS: Weighted<number>[] = [
  {
    "value": 0,
    "weight": 0.46
  },
  {
    "value": 1,
    "weight": 0.3
  },
  {
    "value": 2,
    "weight": 0.14
  },
  {
    "value": 3,
    "weight": 0.06
  },
  {
    "value": 5,
    "weight": 0.03
  },
  {
    "value": 8,
    "weight": 0.01
  }
];
export const OUTCOME_MIX: Weighted<string>[] = [
  {
    "value": "Verified",
    "weight": 0.8
  },
  {
    "value": "Pending Verification",
    "weight": 0.13
  },
  {
    "value": "Rejected",
    "weight": 0.04
  },
  {
    "value": "In Progress",
    "weight": 0.03
  }
];

/** What a record must itself hold for a verifier to have sent it back with this reason. */
export type RejectionGround = "adhesive-batch-written" | "certificate-ref-blank" | "checker-written" | "checkpoint-8-location-blank" | "customer-sign-blank" | "out-of-band-no-remark-column" | "out-of-band-remark-blank" | "pc-05-counted" | "shift-and-operator-written" | "three-quantities-blank" | "time-of-checking-blank" | "two-of-13-counts-blank";
export interface RejectionReason { reason: string; when: RejectionGround; }
/** Given only to a record that holds the reason's grounds (engine/plantSimulation.ts). */
export const REJECTION_REASONS: Record<string, RejectionReason[]> = {
  "daily-pest-monitoring": [
    {
      "reason": "Time of checking left blank — please complete before re-submitting.",
      "when": "time-of-checking-blank"
    },
    {
      "reason": "Check point 8 answered Yes but the location was not written in.",
      "when": "checkpoint-8-location-blank"
    },
    {
      "reason": "Checker name does not match the person who did the round.",
      "when": "checker-written"
    }
  ],
  "fly-catcher": [
    {
      "reason": "Catch count for PC-05 does not match the board photographed at cleaning.",
      "when": "pc-05-counted"
    },
    {
      "reason": "Catch counts entered for 11 of 13 units only.",
      "when": "two-of-13-counts-blank"
    }
  ],
  "service-report": [
    {
      "reason": "Customer's countersignature missing on the visit report.",
      "when": "customer-sign-blank"
    },
    {
      "reason": "Quantity used not recorded against three areas.",
      "when": "three-quantities-blank"
    }
  ],
  "log-sheet": [
    {
      "reason": "Out-of-band reading not explained in the Remark column.",
      "when": "out-of-band-remark-blank"
    },
    {
      "reason": "Out-of-band reading with nothing recorded about it — note what was done before re-submitting.",
      "when": "out-of-band-no-remark-column"
    },
    {
      "reason": "Shift and operator name do not match the production plan.",
      "when": "shift-and-operator-written"
    },
    {
      "reason": "Batch number of the adhesive drum not updated after the change-over.",
      "when": "adhesive-batch-written"
    }
  ],
  "training-record": [
    {
      "reason": "Attendance sheet reference not attached.",
      "when": "certificate-ref-blank"
    }
  ]
};
/** For a record that holds none of them: nothing written on it, so nothing to contradict. "*" is any other kind. */
export const GENERIC_REJECTION_REASONS: Record<string, string[]> = {
  "daily-pest-monitoring": [
    "Round to be re-checked with the checker before re-submitting."
  ],
  "fly-catcher": [
    "Counts to be re-checked against the boards before re-submitting."
  ],
  "service-report": [
    "Visit report to be re-checked with the technician before re-submitting."
  ],
  "log-sheet": [
    "Entries to be re-checked against the shop-floor sheet before re-submitting.",
    "Sheet to be reviewed by the section in-charge before re-submitting."
  ],
  "training-record": [
    "Attendance to be re-checked against the signed sheet before re-submitting."
  ],
  "*": [
    "Entries to be re-checked before re-submitting."
  ]
};

export const SHIFT_ROSTER = {
  "qc": {
    "day": "Jeni",
    "night": "Singh"
  },
  "lamination": [
    "Gaurav Singh",
    "Mahesh Patel",
    "Suresh Chauhan"
  ],
  "pestChecker": [
    "Roshni",
    "Vijay"
  ],
  "verifier": [
    "Kapila Barad"
  ]
};

// ---------------------------------------------------------------------------
// 6. Service report remarks — what a technician actually writes.

export interface ServiceFinding {
  remark: string;
  raisesFinding: boolean;
  finding?: string;
  correctiveAction?: string;
}

export interface ServiceRemarkModel {
  routine: string[];
  finding: ServiceFinding[];
  findingRate: number;
}

export const SERVICE_REMARKS: Record<string, ServiceRemarkModel> = {
  "rodent": {
    "routine": [
      "No Rodent Trapped",
      "No Rodent Trapped",
      "No Rodent Trapped",
      "Bait consumed - replaced",
      "Glue board replaced"
    ],
    "finding": [
      {
        "remark": "Rodent trapped - removed",
        "raisesFinding": false
      },
      {
        "remark": "Bait cake biting observed - box re-baited",
        "raisesFinding": false
      },
      {
        "remark": "Box found displaced - repositioned",
        "raisesFinding": true,
        "finding": "Rodent bait station found displaced from its marked position during the fortnightly service.",
        "correctiveAction": "Station repositioned as per the pest control layout; housekeeping team briefed."
      },
      {
        "remark": "Entry gap observed - reported",
        "raisesFinding": true,
        "finding": "Gap that could allow pest entry noticed by the service technician during treatment.",
        "correctiveAction": "Gap to be closed by maintenance; verified at the next fortnightly visit."
      }
    ],
    "findingRate": 0.015
  },
  "general": {
    "routine": [
      "-",
      "-",
      "-",
      "Sprayed as per schedule",
      "Cockroach activity nil"
    ],
    "finding": [
      {
        "remark": "Cockroach activity seen - gel applied",
        "raisesFinding": false
      },
      {
        "remark": "Ant trail seen - treated",
        "raisesFinding": false
      },
      {
        "remark": "Open drain point - reported",
        "raisesFinding": true,
        "finding": "Open drain point found in the area during pest control service.",
        "correctiveAction": "Drain covered; area supervisor briefed to keep drain points covered."
      }
    ],
    "findingRate": 0.015
  },
  "fly": {
    "routine": [
      "-",
      "-",
      "-",
      "Fogging done",
      "Nil activity"
    ],
    "finding": [
      {
        "remark": "Fly activity high - extra fogging done",
        "raisesFinding": false
      },
      {
        "remark": "Fly catcher found switched off",
        "raisesFinding": true,
        "finding": "Fly killer unit found switched off during the fortnightly fly control service.",
        "correctiveAction": "Unit switched on; shift in-charge briefed to keep all units energised round the clock."
      }
    ],
    "findingRate": 0.015
  }
};

// ---------------------------------------------------------------------------
// 7. How a deviation becomes a corrective action, and when it closes.

export const CAPA_MODEL = {
  "targetDays": [
    {
      "value": 7,
      "weight": 0.35
    },
    {
      "value": 15,
      "weight": 0.45
    },
    {
      "value": 30,
      "weight": 0.2
    }
  ],
  "closure": [
    {
      "value": "on-time",
      "weight": 0.62
    },
    {
      "value": "late",
      "weight": 0.24
    },
    {
      "value": "open",
      "weight": 0.14
    }
  ],
  "lateDays": [
    {
      "value": 3,
      "weight": 0.5
    },
    {
      "value": 6,
      "weight": 0.3
    },
    {
      "value": 11,
      "weight": 0.2
    }
  ]
};
